rule1 isa etl-rule
	lhs { match $type isa pokemon-type; aggregate (get-value $type as val, get-id $type as id1, identity $type as type)}
	rhs { insert $classification isa pokemon-classification value [val] };